PS C:\Users\vovai\Desktop\midi amp> & C:/Users/vovai/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/vovai/Desktop/midi amp/app.py"
Traceback (most recent call last):
  File "c:\Users\vovai\Desktop\midi amp\app.py", line 2, in <module>
    from flask import Flask, render_template, request, send_file, flash, redirect
ModuleNotFoundError: No module named 'flask'
PS C:\Users\vovai\Desktop\midi amp> & C:/Users/vovai/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/vovai/Desktop/midi amp/app.py"
Traceback (most recent call last):
  File "c:\Users\vovai\Desktop\midi amp\app.py", line 2, in <module>
    from flask import Flask, render_template, request, send_file, flash, redirect
ModuleNotFoundError: No module named 'flask'
PS C:\Users\vovai\Desktop\midi amp> pip install -r requirements.txt
Collecting Flask==2.0.3 (from -r requirements.txt (line 1))
  Using cached Flask-2.0.3-py3-none-any.whl.metadata (3.8 kB)
Collecting mido==1.2.10 (from -r requirements.txt (line 2))
  Using cached mido-1.2.10-py2.py3-none-any.whl.metadata (3.4 kB)
Collecting python-rtmidi==1.5.2 (from -r requirements.txt (line 3))
  Using cached python-rtmidi-1.5.2.tar.gz (332 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 2
  ╰─> [118 lines of output]
      Collecting mesonpep517@ git+https://gitlab.com/SpotlightKid/mesonpep517.git@rtmidi
        Cloning https://gitlab.com/SpotlightKid/mesonpep517.git (to revision rtmidi) to c:\users\vovai\appdata\local\temp\pip-install-6gvn6tw7\mesonpep517_fba1786f46414e10a91923a911319ccd
        Running command git clone --filter=blob:none --quiet https://gitlab.com/SpotlightKid/mesonpep517.git 'C:\Users\vovai\AppData\Local\Temp\pip-install-6gvn6tw7\mesonpep517_fba1786f46414e10a91923a911319ccd'
        Running command git checkout -b rtmidi --track origin/rtmidi
        branch 'rtmidi' set up to track 'origin/rtmidi'.
        Switched to a new branch 'rtmidi'
        Resolved https://gitlab.com/SpotlightKid/mesonpep517.git to commit 387ec89c0d9365af492ac2cc81d88a0c689e1c1d
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
      ERROR: Exception:
      Traceback (most recent call last):
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
          status = _inner_run()
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
          return self.run(options, args)
                 ~~~~~~~~^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
          return func(self, options, args)
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\commands\install.py", line 379, in run
          requirement_set = resolver.resolve(
              reqs, check_supported_wheels=not options.target_dir
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 76, in resolve
          collected = self.factory.collect_root_requirements(root_reqs)
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 545, in collect_root_requirements
          reqs = list(
              self._make_requirements_from_install_req(
          ...<2 lines>...
              )
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 501, in _make_requirements_from_install_req
          cand = self._make_base_candidate_from_link(
              ireq.link,
          ...<2 lines>...
              version=None,
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
          self._link_candidate_cache[link] = LinkCandidate(
                                             ~~~~~~~~~~~~~^
              link,
              ^^^^^
          ...<3 lines>...
              version=version,
              ^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
          super().__init__(
          ~~~~~~~~~~~~~~~~^
              link=link,
              ^^^^^^^^^^
          ...<4 lines>...
              version=version,
              ^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
          self.dist = self._prepare()
                      ~~~~~~~~~~~~~^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
          dist = self._prepare_distribution()
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
          dist = _get_prepared_distribution(
              req,
          ...<3 lines>...
              self.check_build_deps,
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
          abstract_dist.prepare_distribution_metadata(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
              finder, build_isolation, check_build_deps
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
          self._install_build_reqs(finder)
          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
          build_reqs = self._get_build_requires_wheel()
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
          return backend.get_requires_for_build_wheel()
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\utils\misc.py", line 701, in get_requires_for_build_wheel
          return super().get_requires_for_build_wheel(config_settings=cs)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
          return self._call_hook('get_requires_for_build_wheel', {
                 ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              'config_settings': config_settings
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          })
          ^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
          raise BackendUnavailable(data.get('traceback', ''))
      pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\vovai\AppData\Local\Temp\pip-install-6gvn6tw7\mesonpep517_fba1786f46414e10a91923a911319ccd\mesonpep517\buildapi.py", line 25, in <module>
          from wheel.bdist_wheel import get_platform
      ImportError: cannot import name 'get_platform' from 'wheel.bdist_wheel' (C:\Users\vovai\AppData\Local\Temp\pip-build-env-ema0mzg3\overlay\Lib\site-packages\wheel\bdist_wheel.py)

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\vovai\Desktop\midi amp> python -m pip install --upgrade pip setuptools wheel
>>
Requirement already satisfied: pip in c:\users\vovai\appdata\local\programs\python\python313\lib\site-packages (24.3.1)
Collecting pip
  Downloading pip-25.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: setuptools in c:\users\vovai\appdata\local\programs\python\python313\lib\site-packages (75.5.0)
Collecting setuptools
  Using cached setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
Collecting wheel
  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Downloading pip-25.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.0 MB/s eta 0:00:00
Using cached setuptools-75.8.0-py3-none-any.whl (1.2 MB)
Using cached wheel-0.45.1-py3-none-any.whl (72 kB)
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.5.0
    Uninstalling setuptools-75.5.0:
      Successfully uninstalled setuptools-75.5.0
  Attempting uninstall: pip
    Found existing installation: pip 24.3.1
    Uninstalling pip-24.3.1:
      Successfully uninstalled pip-24.3.1
Successfully installed pip-25.0 setuptools-75.8.0 wheel-0.45.1
PS C:\Users\vovai\Desktop\midi amp> pip install -r requirements.txt
Collecting Flask==2.0.3 (from -r requirements.txt (line 1))
  Using cached Flask-2.0.3-py3-none-any.whl.metadata (3.8 kB)
Collecting mido==1.2.10 (from -r requirements.txt (line 2))
  Using cached mido-1.2.10-py2.py3-none-any.whl.metadata (3.4 kB)
Collecting python-rtmidi==1.5.2 (from -r requirements.txt (line 3))
  Using cached python-rtmidi-1.5.2.tar.gz (332 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 2
  ╰─> [105 lines of output]
      Collecting mesonpep517@ git+https://gitlab.com/SpotlightKid/mesonpep517.git@rtmidi
        Cloning https://gitlab.com/SpotlightKid/mesonpep517.git (to revision rtmidi) to c:\users\vovai\appdata\local\temp\pip-install-gjjmkwh9\mesonpep517_8f1d8885bd594cc586a41c47ac634b88
        Running command git clone --filter=blob:none --quiet https://gitlab.com/SpotlightKid/mesonpep517.git 'C:\Users\vovai\AppData\Local\Temp\pip-install-gjjmkwh9\mesonpep517_8f1d8885bd594cc586a41c47ac634b88'
        Running command git checkout -b rtmidi --track origin/rtmidi
        branch 'rtmidi' set up to track 'origin/rtmidi'.
        Switched to a new branch 'rtmidi'
        Resolved https://gitlab.com/SpotlightKid/mesonpep517.git to commit 387ec89c0d9365af492ac2cc81d88a0c689e1c1d
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
      ERROR: Exception:
      Traceback (most recent call last):
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\base_command.py", line 106, in _run_wrapper
          status = _inner_run()
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\base_command.py", line 97, in _inner_run
          return self.run(options, args)
                 ~~~~~~~~^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
          return func(self, options, args)
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\commands\install.py", line 386, in run
          requirement_set = resolver.resolve(
              reqs, check_supported_wheels=not options.target_dir
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 76, in resolve
          collected = self.factory.collect_root_requirements(root_reqs)
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 545, in collect_root_requirements
          reqs = list(
              self._make_requirements_from_install_req(
          ...<2 lines>...
              )
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 501, in _make_requirements_from_install_req
          cand = self._make_base_candidate_from_link(
              ireq.link,
          ...<2 lines>...
              version=None,
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
          self._link_candidate_cache[link] = LinkCandidate(
                                             ~~~~~~~~~~~~~^
              link,
              ^^^^^
          ...<3 lines>...
              version=version,
              ^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
          super().__init__(
          ~~~~~~~~~~~~~~~~^
              link=link,
              ^^^^^^^^^^
          ...<4 lines>...
              version=version,
              ^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
          self.dist = self._prepare()
                      ~~~~~~~~~~~~~^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
          dist = self._prepare_distribution()
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
          dist = _get_prepared_distribution(
              req,
          ...<3 lines>...
              self.check_build_deps,
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
          abstract_dist.prepare_distribution_metadata(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
              finder, build_isolation, check_build_deps
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
          self._install_build_reqs(finder)
          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
          build_reqs = self._get_build_requires_wheel()
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
          return backend.get_requires_for_build_wheel()
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\utils\misc.py", line 702, in get_requires_for_build_wheel
          return super().get_requires_for_build_wheel(config_settings=cs)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 196, in get_requires_for_build_wheel
          return self._call_hook(
                 ~~~~~~~~~~~~~~~^
              "get_requires_for_build_wheel", {"config_settings": config_settings}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 402, in _call_hook
          raise BackendUnavailable(
          ...<4 lines>...
          )
      pip._vendor.pyproject_hooks._impl.BackendUnavailable: Cannot import 'mesonpep517.buildapi'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\vovai\Desktop\midi amp> & C:/Users/vovai/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/vovai/Desktop/midi amp/app.py"
Traceback (most recent call last):
  File "c:\Users\vovai\Desktop\midi amp\app.py", line 2, in <module>
    from flask import Flask, render_template, request, send_file, flash, redirect
ModuleNotFoundError: No module named 'flask'
PS C:\Users\vovai\Desktop\midi amp> pip uninstall wheel
>>
Found existing installation: wheel 0.45.1
Uninstalling wheel-0.45.1:
  Would remove:
    c:\users\vovai\appdata\local\programs\python\python313\lib\site-packages\wheel-0.45.1.dist-info\*
    c:\users\vovai\appdata\local\programs\python\python313\lib\site-packages\wheel\*
    c:\users\vovai\appdata\local\programs\python\python313\scripts\wheel.exe
Proceed (Y/n)? y
  Successfully uninstalled wheel-0.45.1
PS C:\Users\vovai\Desktop\midi amp> pip install wheel
>>
Collecting wheel
  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Using cached wheel-0.45.1-py3-none-any.whl (72 kB)
Installing collected packages: wheel
Successfully installed wheel-0.45.1
PS C:\Users\vovai\Desktop\midi amp> pip install -r requirements.txt
>>
Collecting Flask==2.0.3 (from -r requirements.txt (line 1))
  Using cached Flask-2.0.3-py3-none-any.whl.metadata (3.8 kB)
Collecting mido==1.2.10 (from -r requirements.txt (line 2))
  Using cached mido-1.2.10-py2.py3-none-any.whl.metadata (3.4 kB)
Collecting python-rtmidi==1.5.2 (from -r requirements.txt (line 3))
  Using cached python-rtmidi-1.5.2.tar.gz (332 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 2
  ╰─> [105 lines of output]
      Collecting mesonpep517@ git+https://gitlab.com/SpotlightKid/mesonpep517.git@rtmidi
        Cloning https://gitlab.com/SpotlightKid/mesonpep517.git (to revision rtmidi) to c:\users\vovai\appdata\local\temp\pip-install-viamxy69\mesonpep517_cffee56277424580b52f27af1ddbbc04
        Running command git clone --filter=blob:none --quiet https://gitlab.com/SpotlightKid/mesonpep517.git 'C:\Users\vovai\AppData\Local\Temp\pip-install-viamxy69\mesonpep517_cffee56277424580b52f27af1ddbbc04'
        Running command git checkout -b rtmidi --track origin/rtmidi
        branch 'rtmidi' set up to track 'origin/rtmidi'.
        Switched to a new branch 'rtmidi'
        Resolved https://gitlab.com/SpotlightKid/mesonpep517.git to commit 387ec89c0d9365af492ac2cc81d88a0c689e1c1d
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
      ERROR: Exception:
      Traceback (most recent call last):
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\base_command.py", line 106, in _run_wrapper
          status = _inner_run()
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\base_command.py", line 97, in _inner_run
          return self.run(options, args)
                 ~~~~~~~~^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
          return func(self, options, args)
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\commands\install.py", line 386, in run
          requirement_set = resolver.resolve(
              reqs, check_supported_wheels=not options.target_dir
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 76, in resolve
          collected = self.factory.collect_root_requirements(root_reqs)
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 545, in collect_root_requirements
          reqs = list(
              self._make_requirements_from_install_req(
          ...<2 lines>...
              )
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 501, in _make_requirements_from_install_req
          cand = self._make_base_candidate_from_link(
              ireq.link,
          ...<2 lines>...
              version=None,
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
          self._link_candidate_cache[link] = LinkCandidate(
                                             ~~~~~~~~~~~~~^
              link,
              ^^^^^
          ...<3 lines>...
              version=version,
              ^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
          super().__init__(
          ~~~~~~~~~~~~~~~~^
              link=link,
              ^^^^^^^^^^
          ...<4 lines>...
              version=version,
              ^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
          self.dist = self._prepare()
                      ~~~~~~~~~~~~~^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
          dist = self._prepare_distribution()
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
          dist = _get_prepared_distribution(
              req,
          ...<3 lines>...
              self.check_build_deps,
          )
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
          abstract_dist.prepare_distribution_metadata(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
              finder, build_isolation, check_build_deps
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
          self._install_build_reqs(finder)
          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
          build_reqs = self._get_build_requires_wheel()
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
          return backend.get_requires_for_build_wheel()
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\utils\misc.py", line 702, in get_requires_for_build_wheel
          return super().get_requires_for_build_wheel(config_settings=cs)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 196, in get_requires_for_build_wheel
          return self._call_hook(
                 ~~~~~~~~~~~~~~~^
              "get_requires_for_build_wheel", {"config_settings": config_settings}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 402, in _call_hook
          raise BackendUnavailable(
          ...<4 lines>...
          )
      pip._vendor.pyproject_hooks._impl.BackendUnavailable: Cannot import 'mesonpep517.buildapi'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\vovai\Desktop\midi amp> pip install --no-build-isolation python-rtmidi
>>
Collecting python-rtmidi
  Downloading python_rtmidi-1.5.8.tar.gz (368 kB)
  Preparing metadata (pyproject.toml) ... done
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\base_command.py", line 106, in _run_wrapper
    status = _inner_run()
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\base_command.py", line 97, in _inner_run
    return self.run(options, args)
           ~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\commands\install.py", line 386, in run
    requirement_set = resolver.resolve(
        reqs, check_supported_wheels=not options.target_dir
    )
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ~~~~~~~~~~~~~~~~^
        collected.requirements, max_rounds=limit_how_complex_resolution_can_be
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
    candidate = func()
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        link, template, name, version
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ~~~~~~~~~~~~~^
        link,
        ^^^^^
    ...<3 lines>...
        version=version,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        link=link,
        ^^^^^^^^^^
    ...<4 lines>...
        version=version,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
    self.dist = self._prepare()
                ~~~~~~~~~~~~~^^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
        req,
    ...<3 lines>...
        self.check_build_deps,
    )
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        finder, build_isolation, check_build_deps
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\distributions\sdist.py", line 69, in prepare_distribution_metadata
    self.req.prepare_metadata()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\req\req_install.py", line 575, in prepare_metadata
    self.metadata_directory = generate_metadata(
                              ~~~~~~~~~~~~~~~~~^
        build_env=self.build_env,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
        backend=self.pep517_backend,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        details=details,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\operations\build\metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_internal\utils\misc.py", line 723, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        metadata_directory=metadata_directory,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        config_settings=cs,
        ^^^^^^^^^^^^^^^^^^^
        _allow_fallback=_allow_fallback,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 224, in prepare_metadata_for_build_wheel
    return self._call_hook(
           ~~~~~~~~~~~~~~~^
        "prepare_metadata_for_build_wheel",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        },
        ^^
    )
    ^
  File "C:\Users\vovai\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 402, in _call_hook
    raise BackendUnavailable(
    ...<4 lines>...
    )
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Cannot import 'mesonpy'
PS C:\Users\vovai\Desktop\midi amp> python --version
Python 3.13.0